# Generated by Django 3.2.19 on 2026-05-07 14:12

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taiga.base.db.models.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0068_add_priority_custom_attribute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('academic_year', models.PositiveIntegerField()),
                ('term', models.CharField(choices=[('Q1', 'First Quarter'), ('Q2', 'Second Quarter'), ('ANNUAL', 'Annual')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='PLANNED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_editions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year', 'term', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academics.courseedition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group_code'],
                'unique_together': {('course_edition', 'group_code')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_code', models.CharField(blank=True, default='', max_length=50)),
                ('global_role', models.CharField(choices=[('ACADEMIC_ADMIN', 'Academic Administrator'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('is_active_teacher', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='GroupProjectLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('course_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_link', to='academics.coursegroup')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_links', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_group_links', to='projects.project')),
            ],
            options={
                'ordering': ['course_group'],
            },
        ),
        migrations.CreateModel(
            name='EditionProfessorAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_assignments', to='academics.courseedition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_professor_assignments', to=settings.AUTH_USER_MODEL)),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_assignments', to='academics.teacherprofile')),
            ],
            options={
                'ordering': ['course_edition', 'teacher_profile'],
                'unique_together': {('course_edition', 'teacher_profile')},
            },
        ),
        migrations.CreateModel(
            name='CourseMetricsPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_to_students_metric_ids', taiga.base.db.models.fields.json.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('hidden_metric_ids', taiga.base.db.models.fields.json.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('group_metric_order', taiga.base.db.models.fields.json.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('project_metric_order', taiga.base.db.models.fields.json.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('allow_student_drilldown', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_policy', to='academics.courseedition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_metrics_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course_edition'],
            },
        ),
        migrations.AddField(
            model_name='courseedition',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='academics.subject'),
        ),
        migrations.CreateModel(
            name='SubjectCoordinatorAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coordinator_assignments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_assignments', to='academics.subject')),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_subjects', to='academics.teacherprofile')),
            ],
            options={
                'ordering': ['subject', 'teacher_profile'],
                'unique_together': {('subject', 'teacher_profile')},
            },
        ),
        migrations.CreateModel(
            name='ProfessorGroupAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_assignments', to=settings.AUTH_USER_MODEL)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_assignments', to='academics.coursegroup')),
                ('edition_professor_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='academics.editionprofessorassignment')),
            ],
            options={
                'ordering': ['edition_professor_assignment', 'course_group'],
                'unique_together': {('edition_professor_assignment', 'course_group')},
            },
        ),
        migrations.CreateModel(
            name='CourseDashboardReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('course_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_readers', to='academics.courseedition')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_dashboard_reads', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readable_editions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course_edition', 'user'],
                'unique_together': {('course_edition', 'user')},
            },
        ),
    ]
