# Generated by Django 3.2.19 on 2025-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_projectmetricssnapshot'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectmetricssnapshot',
            name='metrics_sn_project_f0c554_idx',
        ),
        migrations.AddIndex(
            model_name='projectmetricssnapshot',
            index=models.Index(fields=['project', 'provider', '-computed_at'], name='metrics_pro_project_e501e0_idx'),
        ),
    ]
